import { Inter } from "next/font/google";
import "./globals.scss";

export const metadata = {
  title: "FindMyPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h3 className="title">FindMyPlace</h3>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
